healthcheck-producer-config:
  bootstrap_servers:
    - "localhost:9092"
  websites:
    - url: https://www.google.com
      polling_interval_in_seconds: 30
      regex: .*google.*
      destination_topic: healthcheck-topic-cloud-providers
    - url: https://www.amazon.com
      polling_interval_in_seconds: 10
      regex: .*amazon.*
      destination_topic: healthcheck-topic-cloud-providers
healthcheck-consumer-config:
  bootstrap_servers:
    - "localhost:9092"
  group_id: healthcheck-cloud-group
  auto_offset_reset: earliest
  topics:
    - source_topic: healthcheck-topic-cloud-providers
      connection_uri: "postgresql://admin:admin@localhost:5432/healthcheck"
      table_name: healthcheck
    - source_topic: healthcheck-topic-cloud-providers
      connection_uri: "postgresql://admin:admin@localhost:5432/healthcheck"
      table_name: healthcheckReplica