healthcheck-producer-config:
  bootstrap_servers:
    - !ENV ${KAFKA_BOOTSTRAP_SERVER}
  security_protocol: "SSL"
  ssl_cafile: !ENV ${CA_FILE}
  ssl_certfile: !ENV ${CERT_FILE}
  ssl_keyfile: !ENV ${KEY_FILE}
  websites:
    - url: https://www.google.com
      polling_interval_in_seconds: 30
      regex: .*google.*
      destination_topic: healthcheck-topic-cloud-providers
    - url: https://www.amazon.com
      polling_interval_in_seconds: 10
      regex: .*amazon.*
      destination_topic: healthcheck-topic-cloud-providers
healthcheck-consumer-config:
  bootstrap_servers:
    - !ENV ${KAFKA_BOOTSTRAP_SERVER}
  group_id: healthcheck-cloud-group
  auto_offset_reset: earliest
  security_protocol: "SSL"
  ssl_cafile: !ENV ${CA_FILE}
  ssl_certfile: !ENV ${CERT_FILE}
  ssl_keyfile: !ENV ${KEY_FILE}
  topics:
    - source_topic: healthcheck-topic-cloud-providers
      connection_uri: !ENV ${POSTGRES_CONNECTION_URI}
      table_name: HealthCheck
    - source_topic: healthcheck-topic-cloud-providers
      connection_uri: !ENV ${POSTGRES_CONNECTION_URI}
      table_name: HealthCheckReplica