on:
  push:
    branches:
      - master
      - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
  build-docker-image:
    needs: release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get tags
        run: git fetch --tags origin
      - name: Git Semantic Version
        id: version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          change_path: "python_quickstart_repo"
          bump_each_commit: true
      - name: Build docker images using QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: eliax1996/python-quickstart-project:${{ steps.version.outputs.version }}